name: Day-3-yml
on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: linting the code
        run: echo "Linting code"
        
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the code
        run: echo "Building projects"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: echo "Running tests"        
          
