name: Day-6-yml

on:
  push:
    branches: [main]

jobs:
  context-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
            
      - name: Print repository name
        run: |
          echo "The repository name is : ${{ github.repository }}"

      - name: Print branch name
        run: |
          echo "The branch name is : ${{github.ref_name}}"     
          
      - name: Print who triggered workflow
        run: |
          echo "The workflow is triggered : ${{github.actor}}"
