name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
        environment:
            description: "Select environment"
            required: true
            default: "staging"

jobs:
    manual-test:
        runs-on: ubuntu-latest
        
        steps:
         - name: Print Manual environment
           run: |
             echo "Selected environment is: ${{ github.event.inputs.environment }}"