name : Matrix-Strategy-test

on:
  push:
    branches: [main]

jobs:
  Matrix-strategy:
    runs-on: ${{ matrix.os }}

    strategy:
        fail-fast: false
        matrix:
            os: [ubuntu-latest,windows-latest]
            python-version: [3.10, 3.11, 3.12]

            exclude:
                - os : windows-latest
                  pyhton-version: 3.10


    steps:
        - name: Maximum version
          run : |  
            echo "Running versions: ${{ matrix.python-version }}"        

